framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        paths:
            - '%kernel.project_dir%/src/Sezane/Shop/Infrastructure/Resources/translations'
            - '%kernel.project_dir%/src/Sezane/Product/Infrastructure/Resources/translations'