version: '3'

services:
  nginx-sezane:
    container_name: nginx-sezane
    image: nginx:latest
    volumes:
      - ${SRC_FOLDER}:/var/www
      - ./cfg/sezane.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8.1-fpm
    ports:
      - "9080:80"

  php8.1-fpm:
    container_name: php-8.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${SRC_FOLDER}:/var/www
      - ./cfg/php.ini:/usr/local/etc/php/conf.d/888-pmi.ini
      - ./cfg/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      - PHP_IDE_CONFIG=serverName=xdebug-docker

  mariadb-sezane:
    container_name: mariadb-sezane
    image: mariadb:10.5.8
    ports:
      - "8306:3306"
    volumes:
      - ${SRC_FOLDER_MARIADB}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: boutique
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345

  phpmyadmin-sezane:
    container_name: phpmyadmin-sezane
    depends_on:
      - mariadb-sezane
    image: phpmyadmin/phpmyadmin
    ports:
      - "7080:80"
    environment:
      MYSQL_ROOT_PASSWORD: sezane
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      PMA_USER: admin
      PMA_PASSWORD: 12345
      PMA_HOSTS: mariadb-sezane